server:
  port: 8082

spring:
  application:
    name: ARRIVAL-API

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

auth-service:
  base-url: ${AUTH_SERVICE_BASE_URL:http://localhost:8081}